- name: Check terragrunt version
  changed_when: "version.rc != 0 or terragrunt_version not in version.stdout"
  failed_when: False
  register: version
  command: terragrunt -v

- name: Install terragrunt
  become: true
  when: version is changed
  get_url:
    dest: /usr/bin/terragrunt
    mode: "755"
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_version }}/{{ terragrunt_binary }}"
